sonar.projectKey=challenge-backend
sonar.working.directory=C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend
sonar.pullrequest.cache.basepath=C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend

1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.projectKey=challenge-backend:1638F4E5-68A0-4149-A1B2-82687F4265EE
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.projectName=ChallengeIntuit-Backend
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.projectBaseDir=C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.sourceEncoding=utf-8
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.tests=
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.sources=\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\Controllers\\ClientesController.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\Data\\AppDbContext.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\Models\\Cliente.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\Models\\ClienteDto.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\Program.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\ChallengeIntuit-Backend.GlobalUsings.g.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\ChallengeIntuit-Backend.AssemblyInfo.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\ChallengeIntuit-Backend.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\appsettings.Development.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\appsettings.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend.http",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\logs\\log-20251206.txt",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\Properties\\launchSettings.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\ChallengeIntuit-Backend.csproj.nuget.dgspec.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\project.assets.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\bin\\Debug\\net8.0\\ChallengeIntuit-Backend.deps.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\bin\\Debug\\net8.0\\ChallengeIntuit-Backend.runtimeconfig.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\bin\\Debug\\net8.0\\ChallengeIntuit-Backend.staticwebassets.endpoints.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\obj\\Debug\\net8.0\\EndpointInfo\\ChallengeIntuit-Backend.json"

1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\.sonarqube\\out\\0"
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\.sonarqube\\out\\0\\Issues.json"
1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.cs.scanner.telemetry=\
"C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\.sonarqube\\out\\0\\Telemetry.json"

1638F4E5-68A0-4149-A1B2-82687F4265EE.sonar.working.directory=C:\\Users\\samtr\\source\\repos\\ChallengeIntuit-Backend\\ChallengeIntuit-Backend\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=1638F4E5-68A0-4149-A1B2-82687F4265EE

